---
engines:
  duplication:
     enabled: false
  eslint:
    enabled: true
    config:
      config: .eslintrc
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 6
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 200
ratings:
  paths:
  - "**.js"
exclude_paths:
- "app/src/main/res/js/materialize.js"
