sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1 NODE_VERSION=7
      compiler: clang

node_js:
  - 7

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - libgnome-keyring-dev
      - xz-utils
      - xorriso
      - xvfb

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

install:
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
  - npm install -g yarn --cache-min 999999999
  - yarn install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - yarn ci:all
  - yarn ci:deploy