language: java

jdk:
  - oraclejdk8

os:
  - linux

notifications:
  slack: devrantfx:LB3S4jRiLEisGc71acoCZlnr

before_install:
 - chmod +x gradlew

script:
  - ./gradlew assemble
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)