sudo: required
language: node_js

addons:
  apt:
    packages:
      - clang
      - g++-4.8
      - icnsutils
      - libgnome-keyring-dev

matrix:
  include:
    - os: linux
      env: NODE_VERSION=7.7.3 CC=gcc-4.8 CXX=gcc-4.8
    - os: osx
      env: NODE_VERSION=7.7.3 CC=clang CXX=clang++

cache:
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.yarn-cache"
  
before_install:
  - npm install -g yarn  --cache-min 999999999
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi

install:
  - yarn install
  - yarn ci:all
  - yarn ci:deploy