language: java

jdk:
  - oraclejdk8

os:
  - linux

notifications:
  slack: devrantfx:LB3S4jRiLEisGc71acoCZlnr

branches:
  only:
    - master

before_install:
 - chmod +x gradlew

script:
  - ./gradlew assemble