sudo: required
dist: trusty

osx_image: xcode8.3

language: node_js
node_js: "9"

os:
  - linux
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

install:
- yarn

script:
- npm rebuild node-sass
- yarn lint
- yarn test
- yarn build

after_script: cat ./coverage/lcov.info | coveralls

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then npm run publish; fi
