os: unstable

# cache yarn and node_modules folder for rebuilds
cache:
  - node_modules

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

configuration: Release

# The environment configurations. We will use the latest node version.
environment:
  # the token is encrypted by appveyor. No need to hide it.
  GH_TOKEN:
    secure: F+HS8KZxRNTuVHrgvn7qtG+NmS6LLCWoWYndsvG2Ru+zr6D6SMD5FsGAZmRCGwnQ
  matrix:
    - NODE_VERSION: 8

# make sure we are running on 64bit
platform:
  - x64

# if one build fails, fail all builds.
matrix:
  fast_finish: true

# we only need node (64bit) and yarn (preinstalled)
install:
  - ps: Install-Product node $env:NODE_VERSION x64
  - set CI=true
  - npm i

before_build:
  - npm run lint

build_script:
  - npm run build

test: off
deploy: off

# only deploy on success and if we are on the master branch
-
  branches:
    only:
      - master
  on_success:
    - IF %APPVEYOR_REPO_BRANCH%==master npm run publish
