name: devrantron
version: 1.2.0
summary: devRantron
description: An open source cross platform desktop application for devRant
confinement: strict
grade: stable
icon: snap/gui/icon.png
apps:
  devrantron:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/devrantron
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
parts:
  app:
    plugin: dump
    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
    source: ./release/linux-unpacked
    after:
      - desktop-glib-only
